### ISSUE TITLE
Privilege 'UPDATE' has wrong identifier

### ISSUE THREAD

**Issue by moertel** [moertel/forty#1]
Granting `update` privilege to a user breaks the sync:
```diff
11:26:33 | grunwald☂ glados: ~/dev/forty (table-acl-fix *% u=) [#1|+2|-1] $ git diff
diff --git a/example/acl.json b/example/acl.json
index cfb0a2f..07f561b 100644
--- a/example/acl.json
+++ b/example/acl.json
@@ -21,7 +21,8 @@
                     ],
                     "privileges": [
                         "select",
-                        "insert"
+                        "insert",
+                        "update"
                     ]
                 }
             ]
```
```
11:26:08 | grunwald☂ glados: ~/dev/forty (table-acl-fix *% u=) [#1|+2|-1] $ docker-compose -f demo_docker-compose.yml up -d postgres_demo_db
Starting forty_postgres_demo_db_1 ... done
11:26:13 | grunwald☂ glados: ~/dev/forty (table-acl-fix *% u=) [#1|+2|-1] $ docker-compose -f demo_docker-compose.yml run some_app
Starting forty_postgres_demo_db_1 ... done
[Forty] [INFO] Create example schemas and tables
NOTICE:  schema "some_schema" already exists, skipping
NOTICE:  schema "another_schema" already exists, skipping
NOTICE:  relation "some_table" already exists, skipping
NOTICE:  relation "another_table" already exists, skipping
[Forty] [WARN] Dry mode disabled, executing on production
[Forty] [INFO] Starting sync...
    ____           __
   / __/___  _____/ /___  __
  / /_/ __ \/ ___/ __/ / / /
 / __/ /_/ / /  / /_/ /_/ /
/_/  \____/_/   \__/\__, /  Database ACL Sync
                   /____/   v0.3.0

===============================================================================

Running in PRODUCTION-MODE (enforcing state)

Configuration:
    Master user:    demo_admin_user
    Synced schemas: some_schema, another_schema
    System users:   postgres
    System groups:  pg_signal_backend

===============================================================================

rake aborted!
TypeError: no implicit conversion of Array into Integer
/lib/forty/privilege.rb:17:in `slice!'
/lib/forty/privilege.rb:17:in `block in parse_privileges_from_string'
/lib/forty/privilege.rb:15:in `each'
/lib/forty/privilege.rb:15:in `parse_privileges_from_string'
/lib/forty/sync.rb:745:in `block in _parse_current_permissions'
/lib/forty/sync.rb:739:in `each'
/lib/forty/sync.rb:739:in `_parse_current_permissions'
/lib/forty/sync.rb:698:in `block in _parse_current_acl'
/lib/forty/sync.rb:695:in `each'
/lib/forty/sync.rb:695:in `_parse_current_acl'
/lib/forty/sync.rb:484:in `_get_current_table_acl'
/lib/forty/sync.rb:368:in `_revoke_all_privileges'
/lib/forty/sync.rb:348:in `_delete_user'
/lib/forty/sync.rb:77:in `block in sync_users'
/lib/forty/sync.rb:77:in `each'
/lib/forty/sync.rb:77:in `sync_users'
/lib/forty/sync.rb:37:in `run'
/lib/forty/sync.rb:12:in `sync'
/lib/forty/rake/task.rb:15:in `block (3 levels) in install_tasks'
/usr/local/bundle/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => acl:sync:all
(See full trace by running task with --trace)
```

**Comment by moertel** [comment]
For some reason I wrote the update identifier uppercase `W` instead of lowercase `w`. Fixing that resolves the issue:
```diff
11:30:44 | grunwald☂ glados: ~/dev/forty (table-acl-fix *% u=) [#2|+3|-2] $ git diff
diff --git a/lib/forty/privilege.rb b/lib/forty/privilege.rb
index 397bfd8..d4c4b1f 100644
--- a/lib/forty/privilege.rb
+++ b/lib/forty/privilege.rb
@@ -44,7 +44,7 @@ module Forty
     class Table < Base
       ALL = 'arwdDxt'
       SELECT = 'r'
-      UPDATE = 'W'
+      UPDATE = 'w'
       INSERT = 'a'
       DELETE = 'd'
       TRUNCATE = 'D'
```
```
11:30:14 | grunwald☂ glados: ~/dev/forty (table-acl-fix *% u=) [#2|+3|-2] $ docker-compose -f demo_docker-compose.yml run some_app
Starting forty_postgres_demo_db_1 ... done
[Forty] [INFO] Create example schemas and tables
NOTICE:  schema "some_schema" already exists, skipping
NOTICE:  schema "another_schema" already exists, skipping
NOTICE:  relation "some_table" already exists, skipping
NOTICE:  relation "another_table" already exists, skipping
[Forty] [WARN] Dry mode disabled, executing on production
[Forty] [INFO] Starting sync...
    ____           __
   / __/___  _____/ /___  __
  / /_/ __ \/ ___/ __/ / / /
 / __/ /_/ / /  / /_/ /_/ /
/_/  \____/_/   \__/\__, /  Database ACL Sync
                   /____/   v0.3.0

===============================================================================

Running in PRODUCTION-MODE (enforcing state)

Configuration:
    Master user:    demo_admin_user
    Synced schemas: some_schema, another_schema
    System users:   postgres
    System groups:  pg_signal_backend

===============================================================================

[Forty] [INFO] drop user this_user_should_not_exist;
[Forty] [INFO] All groups are in sync
[Forty] [INFO] All user groups are in sync
[Forty] [INFO] All user roles are in sync
[Forty] [INFO] All database privileges are in sync
[Forty] [INFO] All schema privileges are in sync
[Forty] [INFO] All table privileges are in sync
```
